server:
  port: 8080
  servlet:
    application-display-name: local

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "cache"
  endpoint:
    health:
      show-details: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  config:
    activate:
      on-profile: local

  thymeleaf:
    prefix: classpath:/templates/
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

security:
  jwt:
    secret-key: 7YG066aw7L2U65Oc7JmAIO2FjOyKpO2KuOy9lOuTnOulvCDsgqzrnpHtlZjripQgMuuFhOywqCDrsLHsl5Trk5wg6rCc67Cc7J6QIOuwleqxtO2drCDsnoXri4jri6Qu
    access-expiration-time : 60 * 30
    refresh-expiration-time : 60 * 60 * 24 * 14


