server:
  port: 8080
  servlet:
    application-display-name: local

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "cache"
  endpoint:
    health:
      show-details: always

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true




