server:
  port: 8082

spring:
  application:
    name: hanghae-plus-stage
  datasource:
    driver-class-name: # mysql
    url: # stage db 엔드 포인트
    username: # stage db username
    password: # stage db password
