server:
  port: 8080
  servlet:
    application-display-name: local

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "cache"
  endpoint:
    health:
      show-details: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hhp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cony
    password: cony1234
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect




