name: Docker Image CI to ECR - dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  AWS_REGION: ap-northeast-2
  ECS_CLUSTER_NAME: cluster-hhplus-dev



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
          java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew bootjar

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id : ${{secrets.AWS_ACCESS_KEY}}
        aws-secret-access-key : ${{secrets.AWS_SECRET_KEY}}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to AWS ECR
      id: login-ecr
      run: aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{secrets.ECR_DEV_URL}}

    - name: Build the Docker image
      id: build-image
      run: |
       docker build -t hhplus-dev:latest .
       echo "::set-output name=image::${{ secrets.ECR_DEV_URL }}/hhplus-dev:latest"

    - name : ADD Tag
      run : docker tag hhplus-dev:latest ${{secrets.ECR_DEV_URL}}/hhplus-dev:latest
    - name: Push Docker image to ECR
      run: docker push ${{secrets.ECR_DEV_URL}}/hhplus-dev:latest
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS }}
    - name: Render ECS task-definition
      id: render-task-definition
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
       task-definition: task-definition-dev.json
       container-name: hhp-dev
       image: ${{ steps.build-image.outputs.image }}

