name: hanghae-plus-actions

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
          java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew bootjar
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id : ${{secrets.AWS_ACCESS_KEY}}
        aws-secret-access-key : ${{secrets.AWS_SECRET_KEY}}
        aws-region: ap-northeast-2
    - name: Login to AWS ECR
      run: aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 490538782156.dkr.ecr.ap-northeast-2.amazonaws.com
    - name: Build the Docker image
      run: docker build -t hhplus-prod:latest .
    - name : ADD Tag
      run : docker tag hhplus-prod:latest 490538782156.dkr.ecr.ap-northeast-2.amazonaws.com/hhplus-prod:latest
    - name: Push Docker image to ECR
      run: docker push 490538782156.dkr.ecr.ap-northeast-2.amazonaws.com/hhplus-prod:latest
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS }}
